shared:
  image: node:20

jobs:
  second:
    requires: [~pr, ~commit]
    steps:
    - noop: |
        echo "world"
    - teardown-step: |
        echo $(meta get meta.build_status)
        meta set meta.status.first '{"status":"SUCCESS","message":"Coverage is above 80%."}'
  first:
    requires: [~pr, ~commit]
    template: sd/noop@latest
